version: "3"

tasks:
  # Pre-Commit Hook
  precommit:enable:
    desc: "git-hooksを有効化する"
    cmds:
      - chmod +x .githooks/*
      - git config core.hooksPath .githooks/
  precommit:disable:
    desc: "git-hooksを無効化する"
    cmds:
      - git config --unset core.hooksPath

  up:
    desc: "アプリを起動する"
    cmds:
      - npm start

  db:update-schema:
    desc: "データベースのスキーマを更新する"
    dir: ./functions/bloom-socials
    cmds:
      - npm run db:update-schema

  db:migrate:
    desc: "データベースのマイグレーションを実行する"
    dir: ./functions/bloom-socials
    cmds:
      - npx -y wrangler@latest d1 migrations apply bloom-socials --local
